num1, num2, num3= map(int, input().split())

if num3 > num2 > num1:
    print(num1)
    print(num2)
    print(num3)
    print()
    print(num1)
    print(num2)
    print(num3)
elif num3 > num1 > num2:
    print(num2)
    print(num1)
    print(num3)
    print()
    print(num1)
    print(num2)
    print(num3)
elif num1 > num2 > num3:
    print(num3)
    print(num2)
    print(num1)
    print()
    print(num1)
    print(num2)
    print(num3)
elif num2 > num1 > num3:
    print(num3)
    print(num1)
    print(num2)
    print()
    print(num1)
    print(num2)
    print(num3)
elif num2 > num3 > num1:
    print(num1)
    print(num3)
    print(num2)
    print()
    print(num1)
    print(num2)
    print(num3)
elif num1 > num3 > num2:
    print(num2)
    print(num3)
    print(num1)
    print()
    print(num1)
    print(num2)
    print(num3)

